In [33]:
import numpy as np
import pandas as pd

  

In [34]:
x1 =  np.random.randint(low=1,high=20,size=(3,4))
x1
  

array([[17,  8, 18,  5],
       [12,  5,  9, 19],
       [ 3, 16, 11,  7]])

In [35]:
x2= np.random.randint(low=1,high=20,size=(2,3))
x2

array([[ 6, 16, 16],
       [ 3, 13, 15]])

In [36]:
x3= np.random.randint(low=1,high=20,size=(1,2))
x3


array([[ 7, 12]])

In [37]:
x4= np.random.randint(low=1,high=20,size=(0,1))
x4
                  

array([], shape=(0, 1), dtype=int32)

In [52]:
y=

[17, 8, 18, 5] [12, 5, 9, 19] [3, 16, 11, 7] 

In [ ]:
•	Find the angle between a= [ 1 1 0] and b=[1 0 1].
•	Write a python program to check if a point lies inside the circle.
User input : point(x,y) , center of circle(a,b) and radius of circle(r)

•	given a dataset of 10 observations and 5 features, write a program to find the 3 nearest points of a query point.


•	Write python code to find the mean,variance and standard deviation of a vector.

•	Python code to find transpose of a matrix.

•	Python code to find euclidean, manhattan and cosine distance  between 2 vectors.

In [56]:
#transpose the matrix
x4= np.random.randint(low=1,high=20,size=(4,3))
x4

array([[15, 17,  4],
       [ 6,  3, 10],
       [ 3,  2, 14],
       [ 3, 12,  7]])

In [57]:
transpose=x4.T
print(transpose)

[[15  6  3  3]
 [17  3  2 12]
 [ 4 10 14  7]]


In [63]:
#Write python code to find the mean,variance and standard deviation of a vector.
x1=np.random.randint(low=1,high=20,size=(10))

print(x1)


[16  1  7 17 15 14  3  8  7 11]


In [80]:
#assisgment one
#calculate the mean
list1=x1
s=0
mean=0
for i in list1:
    s=(s+i)
    mean=(s/2)
print("mean=",mean,s)


list1.sort()
print(list1)
median=0
for i in list1:
    medain=(list1[6]+list1[7])/2
print("medain=",medain)


mean= 49.5 99
[ 1  3  7  7  8 11 14 15 16 17]
medain= 14.5


In [76]:
c=np.std(x1)
c

5.281098370604357

In [126]:
#find the angle btw them
a=(1,1,1) 
b=(1,0,1)
c=np.dot(a,b)
c


2

In [136]:

def isInside(circle_a, circle_b, r, x, y):
    if ((x - circle_a) * (x - circle_a) +
        (y - circle_b) * (y - circle_b) <= r * r):
        return True
    else:
         return False
x = 4
y = 2
circle_a = 1
circle_b = 5
r = 2
if(isInside(circle_a, circle_b, r, x, y)):
 print("Inside");
else:
 print("Outside");

Outside


In [154]:
l=[1,2,3,4,5]
sum=0
for i in l:
    if i<5:
        print(i)
        sum=(sum+i)
print (sum)
l=[1,2,3,4,5]
sum=0

for i in l:
    if i>1:
        print(i)
        sum=(sum+i)
print(sum)        


    
    



1
2
3
4
10
2
3
4
5
14


In [148]:
l=[1,2,3,4,5]
sum=0
for i in l:
    if i<1:
        print(i)
sum=(sum+i)        



In [147]:
l=[1,2,3,4,5]
sum=0
for i in l:
    if i>1:
        print(i)
        sum=(sum+i)
print(sum)        


2
3
4
5
14


In [ ]:
def is_leap(year):
    leap = False
    if year%4:
        print(" leap year")
    else:
        print(" not a leap year")
        return leap
year = int(input())
    
    
    
    



In [7]:
year=(int(input()))
leap=year%4==0


print(leap)

2020
True


In [ ]:
leap=year%4==0


print(leap)

In [10]:
def is_leap(year):
    leap = False
    leap=year%4==0



    

    
    return leap

year = int(input())
print(is_leap(year))

2024
True


1
2
3
4
10
2
3
4
5
15


In [30]:


    
    
print(sum)

2
3
4
5
15


In [41]:
l=[1,2,3,4,5]
sum=0
for i in l:
    if i<5:
        
        #print(i)
        sum=(sum+i)
print (sum)



        

9


In [ ]:
def max_min()
